# Generated by Django 5.1.1 on 2024-10-09 10:51

import app_bot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField()),
                ('is_notification_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('parts', models.JSONField(default=app_bot.models.default_parts_list)),
                ('ordered_time', models.DateTimeField()),
                ('accepted_time', models.DateTimeField()),
                ('completed_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('ABRAS_MATHERIALS', 'абразивные материалы'), ('POLISHING_WHEELS', 'полировальные круги'), ('PAINTING_TAPES', 'малярные ленты'), ('PLANES', 'рубанки'), ('POLISHING_PASTES', 'полировальные пасты'), ('SPRAY_GUNS', 'краскопульты'), ('SUPPLIES', 'расходные материалы'), ('OTHER', 'другое')], default='OTHER', max_length=16)),
                ('description', models.TextField(max_length=256)),
                ('available_count', models.IntegerField(default=0)),
                ('image', models.FileField(default='img/parts/no_img_part.jpg', upload_to='img/parts')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parts', models.JSONField(default=app_bot.models.default_parts_list)),
                ('ordered_time', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_time', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bot.user')),
            ],
        ),
    ]
