# Generated by Django 5.1.3 on 2025-01-08 12:14

import app_bot.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID админа в тг')),
                ('admin_name', models.CharField(default='админ', max_length=64, verbose_name='имя')),
                ('is_notification_enabled', models.BooleanField(default=True, verbose_name='уведомления включены?')),
            ],
            options={
                'verbose_name': 'админ',
                'verbose_name_plural': 'админы',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID товара')),
                ('is_available', models.BooleanField(default=True, verbose_name='доступен в каталоге?')),
                ('name', models.CharField(default='', max_length=64, verbose_name='имя')),
                ('category', models.CharField(choices=[('abrasive_wheels', '🛠 абразивные круги'), ('abrasive_strips', '🛠 абразивные полоски'), ('trizact_velvet', '🛠 trizact - velvet'), ('washing_paper', '🛠 замывочная бумага'), ('scotch_and_masking_tapes', '🛠 скотчи, малярные ленты'), ('planes', '🛠 рубанки'), ('polishing_wheels', '🛠 полировальные круги'), ('supplies', '🛠 расходные материалы'), ('spray_guns', '🛠 краскопульты'), ('other', '🛠 другое'), ('preorder', '🛠 предзаказ')], default='OTHER', max_length=64, verbose_name='категория')),
                ('description', models.TextField(default='', max_length=256, verbose_name='описание')),
                ('price', models.FloatField(default=0.0, verbose_name='цена')),
                ('available_count', models.PositiveIntegerField(default=0, verbose_name='доступное количество')),
                ('image', models.ImageField(default="img/static/malarka_shop_bot_part_no_image.jpg", max_length=256, upload_to="", verbose_name='фото')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID пользователя в тг')),
                ('username', models.CharField(default='', max_length=64, verbose_name='username пользователя в тг')),
                ('name', models.CharField(default='', max_length=64, verbose_name='имя пользователя')),
                ('phone_number', models.CharField(default='', max_length=9, verbose_name='моб. номер')),
                ('delivery_address', models.CharField(default='', max_length=128, verbose_name='адрес доставки')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='номер заказа')),
                ('parts', models.JSONField(default=dict, verbose_name='товары в корзине')),
                ('cost', models.FloatField(default=0.0, verbose_name='стоимость корзины')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bot.user', verbose_name='пользователь в тг')),
            ],
            options={
                'verbose_name': 'заказ в корзине',
                'verbose_name_plural': 'заказы в корзине',
            },
        ),
        migrations.CreateModel(
            name='ConfirmedOrder',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='номер заказа')),
                ('parts', models.JSONField(default=dict, verbose_name='товары в заказе')),
                ('cost', models.FloatField(default=0.0, verbose_name='стоимость заказа')),
                ('ordered_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='время оформления')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='заказ принят?')),
                ('accepted_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='время принятия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bot.user', verbose_name='пользователь в тг')),
            ],
            options={
                'verbose_name': 'выполняемый заказ',
                'verbose_name_plural': 'выполняемые заказы',
            },
        ),
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='номер заказа')),
                ('parts', models.JSONField(default=dict, verbose_name='товары в заказе')),
                ('cost', models.FloatField(default=0.0, verbose_name='стоимость заказа')),
                ('ordered_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='время оформления')),
                ('accepted_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='время принятия')),
                ('completed_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='время доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bot.user', verbose_name='пользователь в тг')),
            ],
            options={
                'verbose_name': 'доставленный заказ',
                'verbose_name_plural': 'доставленные заказы',
            },
        ),
    ]
